name: Build Base Image

on:
  push:
    # 包含了你现在的 develop 分支，以及常见的 master/main
    branches: [ "develop", "master", "main" ]
  workflow_dispatch: # 允许手动点击触发

env:
  # 【重要修改】这里必须全小写！
  # 我已经帮你把 PandaNewsriver 改成了 pandanewsriver
  IMAGE_NAME: ghcr.io/pandanewsriver/zhuque

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 赋予上传镜像的权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
